### ISSUE TITLE
No Error provided when bot name incorrect

### ISSUE THREAD

**Issue by RobinSmithCA** [awslabs/amazon-lex-bot-export#3]
If the bot name provided doesn't exist there is no message to tell me something went wrong.

   if ( err )
   {
      console.log( "Export failed : " + err );
   }
   else
       console.log(JSON.stringify(botDefinition));

should do the trick.

**Comment by joemastersemison** [comment]
Also, there's no error if it can't pick up your AWS credentials properly either. In general, if there's an error, it just returns null. Would be better to have some error handling in some way. Also, I think I'd prefer using STDERR over console logging to STDOUT (given that the default behavior is to kick the definition out over STDOUT).

**Comment by nhira** [comment]
Thanks for the feedback & the PR folks
