### ISSUE TITLE
Save output to file

### ISSUE THREAD

**Issue by RobinSmithCA** [awslabs/amazon-lex-bot-export#4]
Could we optionally save the definition to a file?  Maybe have the filename default to the bot name + .json (i.e. myBot.json).

**Comment by AmolMavuduru** [comment]
I also have this same question. I get the output in my terminal but was unable to save it to a file without doing some kind of brute force copy and paste method. It would be convenient to save this to a file.

**Comment by nhira** [comment]
Something like this should work -- I'll update the README:
```bash
$ node exportlexbot.js <BotName> <BotVersion> | jq '.' > bot.json
```

**Comment by RobinSmithCA** [comment]
This doesn't work for me, I get a message like so:
stdout is not a tty

I'm not sure if this is a local issue or something else.
